const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),csp=JSON.parse(fs.readFileSync(path.join(root,'src-tauri/tauri.conf.json'),'utf8')).app.security.csp;
test('desktop CSP renders real Pixi devices and report preview without unsafe eval',async()=>{
  assert.doesNotMatch(csp,/'unsafe-eval'/);const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();res.setHeader('Content-Security-Policy',csp);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');fs.readFile(file,(error,bytes)=>error?res.writeHead(404).end():res.end(bytes));});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:'msedge'});
  try{const page=await browser.newPage({viewport:{width:1440,height:950}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>{window.policyViolations=[];document.addEventListener('securitypolicyviolation',event=>window.policyViolations.push(event.effectiveDirective));});await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.RackStudio?.PixiContext?.deviceContainers?.size>0);
    await page.evaluate(()=>window.RackStudio.DeliveryUI.open());await page.locator('#delivery-dialog [data-action="freeze"]').click();await page.locator('#delivery-dialog [data-action="preview"]').click();await page.waitForFunction(()=>document.querySelector('#delivery-dialog iframe')?.contentDocument?.body?.textContent.length>100);
    await page.screenshot({path:path.join(root,'docs/product-plan/results/p22-p31/desktop-csp.png')});assert.deepEqual(await page.evaluate(()=>window.policyViolations),[]);assert.deepEqual(errors,[]);
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
});
