const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url'),{chromium}=require('playwright');
const base=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/product/project-rich-v1.json'),'utf8'));
async function setup(browser,legacy=false){const page=await browser.newPage({viewport:{width:1440,height:950}});page.setDefaultTimeout(7000);await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.waitForSelector('.studio-editor[data-ready="true"]');const doc=structuredClone(base);doc.evidenceRefs=[];doc.fieldEvents=[];if(!legacy)delete doc.topology.racks[0].devices[0].observed;await page.evaluate(async doc=>{const R=window.RackStudio;R.loadCustomTopology(doc);await R.saveProjectNow();},doc);return page;}
async function plan(page){return page.evaluate(()=>{const R=window.RackStudio,doc=R.ProjectCommands.semanticDocument(R.ProjectDocument.capture(R.STATE));for(const r of doc.topology.racks)for(const d of r.devices)delete d.observed;return JSON.stringify(doc.topology);});}
async function importFile(page,rows,name='observations.json'){await page.evaluate(()=>window.RackStudio.InventoryImport.open());await page.locator('#inventory-import-file').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(rows))});await page.waitForFunction(()=>!document.querySelector('[data-inventory-action="apply"]').disabled);await page.getByRole('button',{name:'Seçili gözlemleri kaydet',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('inventory-import-dialog').open);}
const records=page=>page.evaluate(()=>window.RackStudio.ProjectDocument.capture(window.RackStudio.STATE).observations);

test('immutable file history retains raw source/time, repeat import is idempotent and stale arrivals preserve the plan',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser),before=await plan(page);const newer={instanceId:'device-1',hostname:'NEW',ipAddress:'192.0.2.8',portId:'p1',description:'Saha tanımı',vlan:'88',status:'up',collectedAt:new Date().toISOString(),vendor:{original:true}};
 await importFile(page,[newer]);const first=await records(page),revision=await page.evaluate(()=>window.RackStudio.STATE.projectDocument.revision);assert.equal(first.length,2);assert.deepEqual(first[1].raw,newer);assert.ok(first[1].source.sha256);assert.ok(first[1].receivedAt);assert.equal(await plan(page),before);
 await importFile(page,[newer]);assert.equal((await records(page)).length,2);assert.equal(await page.evaluate(()=>window.RackStudio.STATE.projectDocument.revision),revision);
 await importFile(page,[{...newer,hostname:'OLD',collectedAt:'2020-01-01T00:00:00Z'}],'old.json');assert.equal((await records(page)).length,3);assert.equal(await page.evaluate(()=>window.RackStudio.STATE.racks[0].devices[0].observed.hostname),'NEW');assert.equal(await plan(page),before);
 await page.evaluate(()=>window.RackStudio.setStudioMode(true));await page.evaluate(()=>window.RackStudio.setStudioMode(false));assert.equal((await records(page)).length,3);await page.evaluate(async()=>{const R=window.RackStudio;await R.saveProjectNow();await R.ProjectRepository.release(R.STATE.projectDocument.projectId);});await page.reload();await page.waitForSelector('.studio-editor[data-ready="true"]');assert.equal((await records(page)).length,3);assert.equal(await plan(page),before);
 }finally{await browser.close();}
});

test('unmatched and ambiguous records remain reviewable and explicit mapping appends a correction',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser);await page.evaluate(async()=>{const R=window.RackStudio,doc=R.ProjectDocument.capture(R.STATE);doc.topology.racks[0].devices.forEach(d=>d.serialNumber='DUP');R.loadCustomTopology(doc);await R.saveProjectNow();});const before=await plan(page);
 await importFile(page,[{instanceId:'missing',hostname:'raw-name'},{serialNumber:'DUP',ipAddress:'192.0.2.19'},{instanceId:'device-1',portId:'not-a-port',status:'up'}]);const rows=await records(page);assert.deepEqual(rows.slice(-3).map(r=>r.mapping.status),['unmatched','ambiguous','unmatched']);assert.equal(await plan(page),before);
 await page.evaluate(id=>window.RackStudio.FieldObservationUI.open(undefined,id),rows[1].id);const dialog=page.getByRole('dialog',{name:'Gözlem geçmişi',exact:true});await dialog.getByLabel('Gözlemi eşle').selectOption('device-2');await dialog.getByRole('button',{name:'Eşlemeyi yeni kayıt olarak kaydet'}).click();await page.waitForFunction(()=>!document.getElementById('field-observations-dialog').hasAttribute('aria-busy'));
 const corrected=(await records(page)).at(-1);assert.equal(corrected.parentObservationId,rows[1].id);assert.equal(corrected.entityRef.id,'device-2');assert.deepEqual(corrected.raw,rows[1].raw);assert.equal(await plan(page),before);const copy=await page.evaluate(()=>{const R=window.RackStudio,doc=R.ProjectManagement.duplicateDocument(R.ProjectDocument.capture(R.STATE)).document,child=doc.observations.find(o=>o.parentObservationId);return {parent:doc.observations.some(o=>o.id===child.parentObservationId),candidate:child.mapping.candidateIds.includes(child.entityRef.id),raw:child.raw};});assert.equal(copy.parent,true);assert.equal(copy.candidate,true);assert.deepEqual(copy.raw,corrected.raw);await page.keyboard.press('Escape');const foreign=await page.evaluate(async()=>{const R=window.RackStudio,expected=R.ProjectManagement.prepare(),rows=await R.FieldObservations.prepare([{instanceId:'device-1',hostname:'FOREIGN'}],{system:'test'});await R.ProjectManagement.create('Başka proje');try{await R.FieldObservations.importRecords(rows,expected);return false;}catch{return R.STATE.projectDocument.observations.length===0;}});assert.equal(foreign,true);
 }finally{await browser.close();}
});

test('selected differences change only selected plan fields and require explicit stale approval',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser);await importFile(page,[{instanceId:'device-1',hostname:'STALE',ipAddress:'192.0.2.99',portId:'p1',vlan:'88',description:'Changed',collectedAt:'2020-01-01T00:00:00Z'}]);const row=(await records(page)).at(-1),history=JSON.stringify(await records(page));await page.evaluate(id=>window.RackStudio.FieldObservationUI.open(undefined,id),row.id);const dialog=page.getByRole('dialog',{name:'Gözlem geçmişi',exact:true});assert.match(await dialog.textContent(),/Eski tarihli gözlem/);
 await dialog.getByLabel('IP adresi',{exact:true}).check();await dialog.getByRole('button',{name:'Seçilen farkları plana uygula'}).click();await page.waitForFunction(()=>!document.getElementById('field-observations-dialog').hasAttribute('aria-busy'));assert.match(await dialog.locator('[role=status]').textContent(),/açık onay/);
 await dialog.getByLabel('Eski gözlemi uygulamayı onaylıyorum').check();await dialog.getByRole('button',{name:'Seçilen farkları plana uygula'}).click();await page.waitForFunction(()=>!document.getElementById('field-observations-dialog').hasAttribute('aria-busy'));
 const d=await page.evaluate(()=>window.RackStudio.STATE.racks[0].devices[0]);assert.equal(d.ipAddress,'192.0.2.99');assert.equal(d.hostname,'edge-1');assert.equal(d.portsConfig.p1.vlan,'99');assert.equal(JSON.stringify(await records(page)),history);
 await dialog.getByLabel('VLAN',{exact:true}).check();await dialog.getByLabel('Eski gözlemi uygulamayı onaylıyorum').check();await dialog.getByRole('button',{name:'Seçilen farkları plana uygula'}).click();await page.waitForFunction(()=>!document.getElementById('field-observations-dialog').hasAttribute('aria-busy'));assert.equal(await page.evaluate(()=>window.RackStudio.STATE.racks[0].devices[0].portsConfig.p1.vlan),'88');assert.equal(await page.evaluate(()=>window.RackStudio.STATE.racks[0].devices[0].portsConfig.p1.description),'Yönetim');
 await page.keyboard.press('Escape');assert.ok((await page.evaluate(()=>window.RackStudio.ProjectChecks.collect())).some(i=>i.text.includes('device.hostname')));
 }finally{await browser.close();}
});

test('legacy migration is repeatable, cable differences validate endpoints and stale envelopes fail',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser,true);await page.evaluate(async()=>{const R=window.RackStudio;R.STATE.racks[0].devices[0].observed.interfaces={p1:{description:'Legacy port',vlan:'10',status:'down'}};await R.saveProjectNow();});const before=await plan(page);await page.evaluate(()=>window.RackStudio.FieldObservations.migrate());const first=await records(page);assert.ok(first.some(r=>r.source?.system==='legacy'&&r.raw.hostname==='observed-edge'));assert.ok(first.some(r=>r.subject?.kind==='port'&&r.raw.description==='Legacy port'));await page.evaluate(()=>window.RackStudio.FieldObservations.migrate());assert.equal((await records(page)).length,first.length);assert.equal(await plan(page),before);
 await importFile(page,[{cableId:'cable-1',medium:'Cat6',measuredLengthMeters:0,from:{rackId:'rack-1',instanceId:'device-1',portId:'missing'}}],'cable.json');const row=(await records(page)).at(-1);const result=await page.evaluate(async id=>{const R=window.RackStudio,O=R.FieldObservations;let rejected=false;try{await O.apply(id,['cable.from'],true);}catch{rejected=true;}await O.apply(id,['cable.medium'],true);const expected=R.ProjectCommands.begin();const doc=R.ProjectDocument.capture(R.STATE);doc.metadata.name='Changed';const cmd=R.ProjectCommands.execute({...R.ProjectCommands.begin(),type:'RestoreProjectDocument',payload:{document:doc}});await cmd.committed;let stale=false;try{await O.apply(id,['cable.from'],true,expected);}catch{stale=true;}return {rejected,stale,cable:R.STATE.cables[0]};},row.id);assert.equal(result.rejected,true);assert.equal(result.stale,true);assert.equal(result.cable.medium,'Cat6');assert.equal(result.cable.from.portId,'p1');assert.equal(result.cable.measuredLengthMeters,0);await importFile(page,[{instanceId:'device-1',catalogKey:'not-in-catalog'}],'model.json');const modelRow=(await records(page)).at(-1),beforeModel=await plan(page);assert.match(await page.evaluate(async id=>{try{await window.RackStudio.FieldObservations.apply(id,['device.catalogKey'],true);return '';}catch(e){return e.message;}},modelRow.id),/bilinmiyor/);assert.equal(await plan(page),beforeModel);
 }finally{await browser.close();}
});

test('history UI fits 320/390/768/1440 and selected metadata entry works in 3D with presentation protection',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser),errors=[];page.on('pageerror',e=>errors.push(e.message));await importFile(page,[{instanceId:'device-1',hostname:'MOBILE',portId:'p1',description:'Mobil saha kaydı',status:'up',collectedAt:'2020-01-01T00:00:00Z'}]);const row=(await records(page)).at(-1);
 await page.evaluate(id=>window.RackStudio.FieldObservationUI.open(undefined,id),row.id);const dialog=page.getByRole('dialog',{name:'Gözlem geçmişi',exact:true});
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});await page.screenshot({path:path.resolve(__dirname,`../docs/product-plan/results/observations-${width}.png`)});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await page.setViewportSize({width:390,height:950});for(const theme of ['light','dark','blueprint','high-contrast']){await page.locator('#btn-theme-toggle').evaluate((el,theme)=>{el.value=theme;el.dispatchEvent(new Event('change',{bubbles:true}));},theme);await page.screenshot({path:path.resolve(__dirname,'../docs/product-plan/results/observations-theme-'+theme+'-390.png')});}await page.setViewportSize({width:1440,height:950});await page.keyboard.press('Escape');await page.evaluate(async()=>{const R=window.RackStudio;await R.setStudioMode(true);window.DeviceMetadataEditor.open3D('device-1');});await page.locator('#modal-device-edit [data-observation-history]').click();await dialog.locator('[data-observation-id='+row.id+']').click();assert.match(await dialog.textContent(),/MOBILE/);await page.keyboard.press('Escape');await page.locator('#btn-close-device-edit').click();
 await page.evaluate(()=>window.RackStudio.WorkflowViews.set('presentation'));assert.match(await page.evaluate(async id=>{try{await window.RackStudio.FieldObservations.apply(id,['device.hostname'],true);return '';}catch(e){return e.message;}},row.id),/Tasarım\/Saha/);assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
