const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url'),{chromium}=require('playwright');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/product/project-rich-v1.json'),'utf8'));
async function setup(browser){const page=await browser.newPage({viewport:{width:1440,height:950}});page.setDefaultTimeout(8000);await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.waitForSelector('.studio-editor[data-ready="true"]');const doc=structuredClone(fixture);doc.evidenceRefs=[];doc.fieldEvents=[];await page.evaluate(async doc=>{const R=window.RackStudio;R.loadCustomTopology(doc);R.setStudioWorkMode("cabling");await R.saveProjectNow();},doc);return page;}
const ref={kind:'cable',id:'cable-1'};
async function record(page,kind,result='pass',extra={},attachment=false){return page.evaluate(async({kind,result,extra,attachment,ref})=>{const R=window.RackStudio;return R.FieldEvents.record({entityRef:ref,kind,result,technician:'Saha teknisyeni',recordedAt:new Date().toISOString(),note:'Yerinde kontrol',...extra},attachment?[new File(['test-result: PASS'],'test.txt',{type:'text/plain'})]:[]);},{kind,result,extra,attachment,ref});}
const status=page=>page.evaluate(ref=>{const R=window.RackStudio;return R.FieldEvents.status(R.ProjectDocument.capture(R.STATE),ref);},ref);
const snapshot=page=>page.evaluate(()=>{const R=window.RackStudio;return R.ProjectDocument.capture(R.STATE);});

test('field state requires application, labels and evidence; corrections and scope changes preserve history',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser),before=await snapshot(page);await assert.rejects(record(page,'test'),/uygulama ve etiketleme/);await record(page,'installed');await record(page,'labeled');assert.equal((await status(page)).complete,false);await assert.rejects(record(page,'test'),/dosyası gerekli/);assert.equal((await snapshot(page)).fieldEvents.length,2);
 await record(page,'test','unknown');assert.equal((await status(page)).label,'Değerlendirilemedi');const unknown=(await snapshot(page)).fieldEvents.at(-1);await assert.rejects(record(page,'test','pass',{},true),/gerekçeli düzeltme/);await record(page,'test','pass',{parentEventId:unknown.id,reason:'Test cihazıyla yeniden ölçüldü'},true);assert.equal((await status(page)).complete,true);const history=(await snapshot(page)).fieldEvents;assert.equal(history[2].result,'unknown');assert.equal(history[3].parentEventId,history[2].id);assert.deepEqual((await snapshot(page)).topology,before.topology);
 await page.evaluate(async()=>{const R=window.RackStudio,d=R.ProjectDocument.capture(R.STATE);d.topology.cables[0].to.portId='p1';const out=R.ProjectCommands.execute({...R.ProjectCommands.begin(),type:'ApplyTopology',payload:{topology:d.topology}});await out.committed;});assert.equal((await status(page)).needsRetest,true);assert.equal((await status(page)).complete,false);
 await page.evaluate(async()=>{const R=window.RackStudio;R.ProjectCommands.execute({...R.ProjectCommands.begin(),type:'RestoreProjectDocument',payload:{document:R.ProjectDocument.normalize({...R.ProjectDocument.capture(R.STATE),fieldEvents:[],evidenceRefs:[]})}});await R.saveProjectNow();});assert.deepEqual((await snapshot(page)).fieldEvents,history);assert.equal((await snapshot(page)).evidenceRefs.length,1);
 }finally{await browser.close();}
});

test('evidence write abort, invalid MIME/signature, stale work and foreign project leave no completed event',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser);await record(page,'installed');await record(page,'labeled');const before=await snapshot(page);
 const failure=await page.evaluate(async ref=>{const R=window.RackStudio,original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='evidence')throw new DOMException('Simulated full disk','QuotaExceededError');return original.apply(this,args);};try{await R.FieldEvents.record({entityRef:ref,kind:'test',result:'pass',technician:'T',recordedAt:new Date().toISOString()},[new File(['proof'],'test.txt',{type:'text/plain'})]);return '';}catch(e){return e.message;}finally{IDBObjectStore.prototype.put=original;}},ref);assert.match(failure,/full disk/);assert.deepEqual((await snapshot(page)).fieldEvents,before.fieldEvents);assert.equal((await snapshot(page)).evidenceRefs.length,0);assert.equal((await status(page)).complete,false);
 const rows=await page.evaluate(async()=>{const R=window.RackStudio;return {head:(await R.ProjectRepository.get(R.STATE.projectDocument.projectId)).document,evidence:await R.ProjectStorageIDB.entries(await R.ProjectRepository.database,'evidence')};});assert.deepEqual(rows.head.fieldEvents,before.fieldEvents);assert.equal(rows.evidence.length,0);
 const badHash=await page.evaluate(async ref=>{const R=window.RackStudio,original=R.FieldEvidence;R.FieldEvidence={...original,prepare:async(...args)=>{const e=await original.prepare(...args);e.refs[0].sha256='0'.repeat(64);return e;}};try{await R.FieldEvents.record({entityRef:ref,kind:'test',result:'pass',technician:'T',recordedAt:new Date().toISOString()},[new File(['proof'],'test.txt',{type:'text/plain'})]);return '';}catch(e){return e.message;}finally{R.FieldEvidence=original;}},ref);assert.match(badHash,/SHA-256/);assert.equal((await snapshot(page)).fieldEvents.length,2);
 const rejects=await page.evaluate(async ref=>{const R=window.RackStudio,out=[];for(const file of [new File(['bad'],'bad.png',{type:'image/png'}),new File(['html'],'bad.html',{type:'text/html'}),new File([],'empty.txt',{type:'text/plain'})]){try{await R.FieldEvents.record({entityRef:ref,kind:'test',result:'pass',technician:'T',recordedAt:new Date().toISOString()},[file]);out.push(false);}catch{out.push(true);}}const old=R.ProjectManagement.prepare();R.STATE.racks[0].devices[0].hostname='changed';await R.saveProjectNow();try{await R.FieldEvents.record({entityRef:ref,kind:'test',result:'pass',technician:'T',recordedAt:new Date().toISOString()},[],old);out.push(false);}catch{out.push(true);}const foreign=R.ProjectManagement.prepare();await R.ProjectManagement.create('Diğer proje');try{await R.FieldEvents.record({entityRef:ref,kind:'test',result:'pass',technician:'T',recordedAt:new Date().toISOString()},[],foreign);out.push(false);}catch{out.push(true);}return out;},ref);assert.deepEqual(rejects,[true,true,true,true,true]);
 }finally{await browser.close();}
});

test('offline save, reload, idempotent retry, 3D roundtrip and verified evidence retain one event',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser);await record(page,'installed');await record(page,'labeled');await page.context().setOffline(true);
 const retry=await page.evaluate(async ref=>{const R=window.RackStudio,expected=R.ProjectManagement.prepare(),input={entityRef:ref,kind:'test',result:'pass',technician:'T',recordedAt:new Date().toISOString()},files=[new File(['PASS'],'test.txt',{type:'text/plain'})];await R.FieldEvents.record(input,files,expected);return R.FieldEvents.record(input,files,expected);},ref);assert.equal(retry.duplicate,true);assert.equal((await snapshot(page)).fieldEvents.length,3);assert.equal((await status(page)).complete,true);
 await page.evaluate(async()=>{const R=window.RackStudio;await R.setStudioMode(true);await R.setStudioMode(false);await R.saveProjectNow();await R.ProjectRepository.release(R.STATE.projectDocument.projectId);});await page.reload();await page.waitForSelector('.studio-editor[data-ready="true"]');assert.equal((await snapshot(page)).fieldEvents.length,3);assert.equal((await status(page)).label,'Kanıt doğrulaması gerekli');const text=await page.evaluate(async()=>{const R=window.RackStudio;return (await R.FieldEvidence.get(R.STATE.projectDocument.evidenceRefs[0])).text();});assert.equal(text,'PASS');assert.equal((await status(page)).complete,true);
 const copy=await page.evaluate(()=>{const R=window.RackStudio,d=R.ProjectManagement.duplicateDocument(R.ProjectDocument.capture(R.STATE)).document;return {scope:R.FieldEvents.scope(d,{kind:'cable',id:d.topology.cables[0].id}),event:d.fieldEvents.at(-1),ref:d.evidenceRefs[0]};});assert.deepEqual(copy.event.scope,copy.scope);assert.equal(copy.event.evidenceIds[0],copy.ref.id);
 const backup=await page.evaluate(async()=>{const R=window.RackStudio,archive=await R.ProjectArchive.exportArchive(),target=new R.ProjectRepositoryClass();target.database=new Promise((resolve,reject)=>{const request=indexedDB.open('field-backup-test',2);request.onupgradeneeded=()=>{for(const name of R.ProjectStorageIDB.STORES)request.result.createObjectStore(name);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});await R.ProjectArchive.importArchive(archive,target);const doc=(await target.get(R.STATE.projectDocument.projectId)).document,evidence=await R.ProjectStorageIDB.read(await target.database,'evidence',[doc.projectId,doc.evidenceRefs[0].blobId]);return {events:doc.fieldEvents,text:await evidence.blob.text()};});assert.deepEqual(backup.events,(await snapshot(page)).fieldEvents);assert.equal(backup.text,'PASS');
 }finally{await browser.close();}
});

test('mobile field form, four themes, evidence verification and presentation protection',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser),errors=[];page.on('pageerror',e=>errors.push(e.message));assert.equal(await page.locator('.field-record-trigger').first().isVisible(),false);await page.evaluate(()=>window.RackStudio.WorkflowViews.set('field'));await page.locator('.field-record-trigger').first().click();const dialog=page.getByRole('dialog',{name:'Saha iş akışı',exact:true});
 await dialog.getByLabel('Teknisyen',{exact:true}).fill('Mobil teknisyen');await dialog.getByRole('button',{name:'Saha kaydını sakla',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('field-workflow-dialog').hasAttribute('aria-busy'));assert.equal((await snapshot(page)).fieldEvents.length,1);assert.equal(await dialog.getByLabel('Saha adımı',{exact:true}).inputValue(),'labeled');
 await dialog.getByLabel('Teknisyen',{exact:true}).fill('Mobil teknisyen');await dialog.getByRole('button',{name:'Saha kaydını sakla',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('field-workflow-dialog').hasAttribute('aria-busy'));await dialog.getByLabel('Teknisyen',{exact:true}).fill('Mobil teknisyen');await dialog.getByLabel('Fotoğraf veya test dosyası',{exact:true}).setInputFiles({name:'mobile-test.txt',mimeType:'text/plain',buffer:Buffer.from('Mobile PASS')});await dialog.getByRole('button',{name:'Saha kaydını sakla',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('field-workflow-dialog').hasAttribute('aria-busy'));assert.equal((await status(page)).complete,true);assert.equal(await dialog.getByRole('button',{name:'Eki indir: mobile-test.txt',exact:true}).count(),1);
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});await page.screenshot({path:path.resolve(__dirname,`../docs/product-plan/results/field-events-${width}.png`)});const fits=await dialog.evaluate(el=>({width:el.scrollWidth,client:el.clientWidth}));assert.ok(fits.width<=fits.client+1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await page.setViewportSize({width:390,height:950});for(const theme of ['light','dark','blueprint','high-contrast']){await page.locator('#btn-theme-toggle').evaluate((el,theme)=>{el.value=theme;el.dispatchEvent(new Event('change',{bubbles:true}));},theme);await page.screenshot({path:path.resolve(__dirname,`../docs/product-plan/results/field-events-theme-${theme}-390.png`)});}await dialog.getByRole('button',{name:'Kapat',exact:true}).click();
 await page.evaluate(()=>window.RackStudio.WorkflowViews.set('presentation'));await page.evaluate(ref=>window.RackStudio.FieldWorkflowUI.open(ref),ref);assert.equal(await dialog.locator('form').count(),0);await assert.rejects(record(page,'labeled'),/Tasarım\/Saha/);assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});

test('device model changes and missing local evidence require renewed validation',async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await setup(browser);await record(page,'installed');await record(page,'labeled');await record(page,'test','pass',{},true);
 const mismatch=await page.evaluate(async()=>{const R=window.RackStudio,ref=R.STATE.projectDocument.evidenceRefs[0];await R.ProjectStorageIDB.transaction(await R.ProjectRepository.database,['evidence'],'readwrite',tx=>tx.objectStore('evidence').delete([R.STATE.projectDocument.projectId,ref.blobId]));try{await R.FieldEvidence.get(ref);return '';}catch(e){return e.message;}});assert.match(mismatch,/yerel depoda yok/);assert.equal((await status(page)).complete,false);
 await page.evaluate(async()=>{const R=window.RackStudio;R.STATE.customCatalog['pilot-switch'].ports[0].name='Changed model port';await R.saveProjectNow();});assert.equal((await status(page)).needsRetest,true);assert.equal((await snapshot(page)).fieldEvents.length,3);
 }finally{await browser.close();}
});
