import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';import {createServer as viteServer} from 'vite';import {chromium} from 'playwright';import {generateKeyPair,SignJWT} from 'jose';
import {migrate} from '../database.mjs';import {Projects} from '../projects.mjs';import {httpServer} from '../http.mjs';import {oidc} from '../auth.mjs';import {Collaboration} from '../collaboration.mjs';import * as domain from '../domain.mjs';
test('two browser sessions rebase independent edits, preserve later drafts, reopen accepted checkpoints and converge annotations',async()=>{
  const pg=new PGlite(),db={query:(...args)=>pg.query(...args),transaction:work=>pg.transaction(tx=>work({query:(sql,args)=>args?.length?tx.query(sql,args):tx.exec(sql).then(values=>values.at(-1)||{rows:[]})}))};await migrate(db);
  await db.query("INSERT INTO companies VALUES('local','Local')");await db.query("INSERT INTO company_members VALUES('local','owner','owner'),('local','designer','member')");
  const source=JSON.parse(await readFile(new URL('../../tests/fixtures/product/project-rich-v1.json',import.meta.url),'utf8')),doc=domain.validate({...source,projectId:'browser-team',revision:0,observations:[],fieldEvents:[],evidenceRefs:[],handoverRecords:[],integrationMappings:[],extensions:{},topology:{...source.topology,racks:[{id:'r',name:'Rack',heightU:18,devices:[]}],cables:[],activeRackId:'r'}});
  const projects=new Projects(db);await projects.create({subject:'owner'},'local',doc);await projects.members({subject:'owner'},doc.projectId,'designer','designer');
  const{privateKey,publicKey}=await generateKeyPair('RS256'),authenticate=oidc({issuer:'https://local-test.test',audience:'rack-studio',keys:publicKey});let collaboration;
  const server=httpServer({projects,authenticate,onCommand:(id,result)=>collaboration.broadcast(id,{type:'accepted',acceptedRevision:result.acceptedRevision})});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const vite=await viteServer({configFile:false,root:new URL('../../',import.meta.url).pathname.replace(/^\/(.:)/,'$1'),server:{host:'127.0.0.1',port:0,strictPort:false,proxy:{'/api':{target:`http://127.0.0.1:${server.address().port}`,ws:true}},watch:{ignored:['**/src-tauri/**','**/docs/**']}}});await vite.listen();const origin=`http://127.0.0.1:${vite.httpServer.address().port}`;collaboration=new Collaboration(server,db,authenticate,[origin]);
  const browser=await chromium.launch({headless:true,channel:'msedge'}),contexts=[];
  const token=subject=>new SignJWT({}).setSubject(subject).setProtectedHeader({alg:'RS256'}).setIssuer('https://local-test.test').setAudience('rack-studio').setIssuedAt().setExpirationTime('10m').sign(privateKey);
  async function client(subject){const context=await browser.newContext(),page=await context.newPage();contexts.push(context);await page.goto(origin);await page.waitForSelector('.studio-editor[data-ready="true"]');await page.evaluate(async({token,id})=>{await window.RackStudio.WorkspaceSession.connect(token);await window.RackStudio.WorkspaceSession.open(id);},{token:await token(subject),id:doc.projectId});return page;}
  async function change(page,metadata){await page.evaluate(async metadata=>{const R=window.RackStudio,current=R.ProjectDocument.capture(R.STATE);const command=R.ProjectManagement.updateDetails(R.ProjectCommands.begin(),{...current.metadata,...metadata},current.locations,current.topology.racks.map(rack=>({rackId:rack.id,locationId:rack.locationId||null})));await command.committed;},metadata);}
  async function send(page){return page.evaluate(async()=>{const S=window.RackStudio.WorkspaceSession,item=await S.enqueue();return S.send(item);});}
  try{
    const left=await client('owner'),right=await client('designer');await change(left,{name:'Local left'});await change(right,{customer:'Remote right'});const sentRight=await send(right);assert.equal(sentRight.ready,true,JSON.stringify(sentRight.conflicts));
    assert.equal(await left.evaluate(()=>window.RackStudio.STATE.projectDocument.metadata.name),'Local left');const sentLeft=await send(left);assert.equal(sentLeft.ready,true,JSON.stringify(sentLeft.conflicts));
    let remote=(await projects.get({subject:'owner'},doc.projectId)).document;assert.equal(remote.metadata.name,'Local left');assert.equal(remote.metadata.customer,'Remote right');
    await change(left,{owner:'Later local edit'});assert.equal((await send(left)).ready,true);remote=(await projects.get({subject:'owner'},doc.projectId)).document;assert.equal(remote.metadata.customer,'Remote right');assert.equal(remote.metadata.owner,'Later local edit');
    await left.evaluate(id=>window.RackStudio.WorkspaceSession.open(id),doc.projectId);assert.equal(await left.evaluate(id=>window.RackStudio.WorkspaceOutbox.read(id).then(rows=>rows.length),doc.projectId),0);
    assert.equal(await left.evaluate(()=>window.RackStudio.STATE.projectDocument.metadata.customer),'Remote right');
    await left.evaluate(()=>window.RackStudio.WorkspaceSession.annotate('left-note','Shared A'));await right.waitForFunction(()=>window.RackStudio.WorkspaceSession.annotations['left-note']==='Shared A');
    await right.evaluate(()=>window.RackStudio.WorkspaceSession.annotate('right-note','Shared B'));await left.waitForFunction(()=>window.RackStudio.WorkspaceSession.annotations['right-note']==='Shared B');
    await left.evaluate(()=>window.RackStudio.WorkspaceSession.disconnect());assert.equal(await left.evaluate(()=>window.RackStudio.WorkspaceSession.connected),false);
  }finally{await browser.close();await collaboration.close();await vite.close();await new Promise(resolve=>server.close(resolve));await pg.close();}
});
